Repository AWS-Cloud-School-6/Recruitment_Front, pull requests merged in 2024-08, with the labels that each got.

#14 #12 [Fix] : 로그인 후 상단 유저 정보 표시
  template/React-Landing-Page-Template/src/App.css
  template/React-Landing-Page-Template/src/components/Apply.jsx
  template/React-Landing-Page-Template/src/components/login.jsx
  template/React-Landing-Page-Template/src/components/myapply.jsx
  template/React-Landing-Page-Template/src/components/navigation.jsx
Labels: enhancement

#15 #13 [Fix] 하드코딩 변경 + 지원내역
  template/React-Landing-Page-Template/package-lock.json
  template/React-Landing-Page-Template/src/components/joblist.jsx
  template/React-Landing-Page-Template/src/components/myapply.jsx
  template/React-Landing-Page-Template/yarn.lock
Labels: bug

#20 #18 Application Change
  .DS_Store
  node_modules/.DS_Store
  template/.DS_Store
  template/React-Landing-Page-Template/src/components/Apply.jsx
  template/React-Landing-Page-Template/src/components/application.jsx
  template/React-Landing-Page-Template/yarn.lock
  template/node_modules/.DS_Store
  template/node_modules/@mui/.DS_Store
Labels: enhancement

#27 26 test 인그레스 테스트를 위한 frontend 이미지 빌드
  template/React-Landing-Page-Template/Dockerfile
  template/React-Landing-Page-Template/src/components/application.jsx
  template/React-Landing-Page-Template/src/components/jobDetails.jsx
  template/React-Landing-Page-Template/src/components/joblist.jsx
  template/React-Landing-Page-Template/src/components/login.jsx
  template/React-Landing-Page-Template/src/components/myapply.jsx
  template/React-Landing-Page-Template/src/components/signup.jsx
Labels: test
